GET http://localhost:5000/users
Authorization: Bearer 

###
POST  http://localhost:5000/users
Content-Type: application/json

{
    "name": "B Luthfian",
    "email": "email@gmail.com",
    "no_hp": "0831-4714-8374",
    "birthdate": "16-09-2023",
    "negara": "Indonesia",
    "domisili": "Kendal",
    "gender": "laki-laki",
    "password": "123456",
    "confPassword": "123456"
}

###
POST  http://localhost:5000/login
Content-Type: application/json

{
    "email": "email@gmail.com",
    "password": "123456"
}


###
GET  http://localhost:5000/token


###
DELETE  http://localhost:5000/logout











http://localhost:5000/user



###
GET http://localhost:5000/user

###
GET http://localhost:5000/user/10

###
POST http://localhost:5000/user
Content-Type: application/json

        {
        "name": "Nakano", 
        "email": "nakano@gmail.com", 
        "negara": "indonesia", 
        "no_hp": "083147148374", 
        "birthdate": "11-09-2023", 
        "domisili": "kendal", 
        "gender": "Male"
        }

###
PATCH http://localhost:5000/user/21
Content-Type: application/json

        {
        "name": "Miku", 
        "email": "nakano@gmail.com", 
        "negara": "Malaysia", 
        "no_hp": "083147148374", 
        "birthdate": "11-09-2022", 
        "domisili": "batam", 
        "gender": "Male"
        }

###
DELETE http://localhost:5000/user/22